# goreleaser.yml
# Release automation
project_name: katzenpost_playground
builds:
  -
    main: ../daemons/mailproxy/main.go
    binary: mailproxy
    flags: |
        -tags netgo -gcflags="-trimpath=$GOPATH" -asmflags="-trimpath=$GOPATH"
    env:
      - CGO_ENABLED=0
    ldflags: |
      -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -extldflags '-static'
    goos:
      - darwin
      - freebsd
      - linux
      - netbsd
      - openbsd
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: 386
  -
    main: ../tools/mailproxy_registration/main.go
    binary: registration
    flags: |
        -tags netgo -gcflags="-trimpath=$GOPATH" -asmflags="-trimpath=$GOPATH"
    env:
      - CGO_ENABLED=0
    ldflags: |
      -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -extldflags '-static'
    goos:
      - darwin
      - freebsd
      - linux
      - netbsd
      - openbsd
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: 386
archive:
  name_template: "{{.ProjectName}}-{{.Version}}-{{.Os}}-{{.Arch}}"
  format: tar.gz
  wrap_in_directory: true
  files:
    - LICENSE
    - README.rst
nfpm:
  vendor: Katzenpost Authors
  homepage: "https://katzenpost.mixnetworks.org/"
  maintainer: "irc://irc.oftc.net/#katzenpost"
  license: AGPL
  formats:
    - deb
    - rpm
sign:
  artifacts: checksum
checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
release:
  github:
    owner: katzenpost
    name: playground
  # If set to true, will not auto-publish the release.
  # Default is false.
  draft: false

  # If set to true, will mark the release as not ready for production.
  # Default is false.
  prerelease: true

  # You can disable this pipe in order to not upload any artifacts to
  # GitHub.
  # Defaults to false.
  disable: false
